# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "OpenAPI"

on:
    schedule:
    # Update Monday
    - cron: "31 04 * * 1"
    workflow_dispatch: null

permissions:
    contents: "write"
    pull-requests: "write"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    generate:
        name: "Generate PHP client"
        runs-on: "ubuntu-latest"
        timeout-minutes: 5
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Set up Java"
            uses: "actions/setup-java@v4"
            with:
                distribution: "temurin"
                java-version: "17"
        -
            name: "Install xmlstarlet"
            run: |
                sudo -- apt-get update
                sudo -- apt-get install -y xmlstarlet
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "8.1"
                tools: "php-cs-fixer"
                coverage: "none"
        -
            name: "Determine OpenAPI CLI version"
            id: "openapi_cli"
            run: |
                VERSION="$(
                    wget -qO- "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/maven-metadata.xml" \
                        | xmlstarlet sel -t -v '//metadata/versioning/versions/version[last()]'
                )"
                echo "version=${VERSION}" >>"${GITHUB_OUTPUT}"
        -
            name: "Determine latest spec version"
            id: "vies_spec"
            run: |
                VERSION="1.0.0"
                echo "version=${VERSION}" >>"${GITHUB_OUTPUT}"
        -
            name: "Install OpenAPI"
            run: |
                wget -O "${{ runner.temp }}/openapi-generator-cli.jar" \
                    "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${{ steps.openapi_cli.outputs.version }}/openapi-generator-cli-${{ steps.openapi_cli.outputs.version }}.jar"
        -
            name: "Clean up previously generated files"
            run: |
                cat .openapi-generator/FILES | xargs -- rm -f -r
        -
            name: "Generate client"
            env:
                PHP_POST_PROCESS_FILE: "php-cs-fixer fix --allow-risky yes"
            run: |
                java -jar "${{ runner.temp }}/openapi-generator-cli.jar" generate \
                    --input-spec ./openapi.yml \
                    --generator-name php-nextgen \
                    --output ./ \
                    --additional-properties 'invokerPackage=Cone\Vies,variableNamingConvention=camelCase,srcBasePath=src'
        -
            name: "Check difference to repository"
            run: |
                if [ -z "$(git status --porcelain)" ]; then
                    echo "No changes!"
                    exit 10
                fi
        -
            name: "Create pull request"
            uses: "peter-evans/create-pull-request@v5"
            with:
                add-paths: "./"
                branch: "php-client"
                commit-message: "Upgrade client"
                title: "Upgrade PHP client to ${{ steps.vies_spec.outputs.version }}"
                body: |
                    Automated changes by running `openapi-generator-cli.jar generate`.
                delete-branch: true
